### ISSUE TITLE
Extension does nothing on Firefox and Chrome

### ISSUE THREAD

**Issue by Jackymancs4** [dword-design/github-saved-filters#12]
Hello @dword-design 

I'm trying your extension and well.. it does nothing. No menu, no saved button.

I've tried version 1.0.4 on Firefox 86. This is the last one available on AMO store, so I guess it's a bit outdated. I've also had no luck with version 1.1.0 in the chrome store on Chrome 88.

The console shows no output what so ever, I have no clue about what might be going wrong.

Is it a know problem, maybe due to recent github redesign activities?

Thanks!

**Comment by Jackymancs4** [comment]
As an example, this line 
https://github.com/dword-design/github-saved-filters/blob/f97138bfb661941e76f853ab5a5810bc4dcd9911/model/build-action-button.js#L9

return always null, as I have not found a `.subnav` element in all the pages I looked in.

**Comment by dword-design** [comment]
Hey @Jackymancs4, I had a look at the issue and could it be that you are in some kind of redesign/beta user group? Because there were no changes in my interface and the `.subnav` elements are in the [/issues](https://github.com/issues) and [/pulls](https://github.com/pulls) routes. See also the screenshot attached. I also checked my installed version in chrome as well as a local checkout.
[
<img width="641" alt="Bildschirmfoto 2021-02-27 um 21 37 12" src="https://user-images.githubusercontent.com/13484795/109399637-540ff100-7944-11eb-859d-ede8e15f1ac6.png">
](url)

**Comment by fharper** [comment]
Anyone found a way to fix the extension?
